version: '{build}'
clone_depth: 10
environment:
  matrix:
    - VIM_URL: http://vim-jp.org/redirects/koron/vim-kaoriya/vim81/oldest/win64/
      THEMIS_PROFILE: vim-profile-win-v8.1.txt
    - VIM_URL: http://vim-jp.org/redirects/koron/vim-kaoriya/latest/win64/
      THEMIS_PROFILE: vim-profile-win-latest.txt
    # To test with latest official Vim binary, uncomment below line.
    #- VIM_URL: http://vim-jp.org/redirects/vim/vim-win32-installer/latest/x64/
install:
  - ps: |
      $zip = $Env:APPVEYOR_BUILD_FOLDER + '\vim.zip'
      $vim = $Env:APPVEYOR_BUILD_FOLDER + '\vim\'
      $redirect = Invoke-WebRequest -URI $Env:VIM_URL
      (New-Object Net.WebClient).DownloadFile($redirect.Links[0].href, $zip)
      [Reflection.Assembly]::LoadWithPartialName('System.IO.Compression.FileSystem') > $null
      [System.IO.Compression.ZipFile]::ExtractToDirectory($zip, $vim)
      $Env:THEMIS_VIM = $vim + (Get-ChildItem $vim).Name + '\vim.exe'
  - 'git -c advice.detachedHead=false clone https://github.com/Shougo/vimproc.vim --quiet --branch ver.9.2 --single-branch --depth 1 %TEMP%\vimproc'
  - 'appveyor DownloadFile https://github.com/Shougo/vimproc.vim/releases/download/ver.9.2/vimproc_win64.dll -FileName %TEMP%\vimproc\lib\vimproc_win64.dll'

  - 'git -c advice.detachedHead=false clone https://github.com/thinca/vim-themis --quiet --branch v1.5.5 --single-branch --depth 1 %TEMP%\vim-themis'
  - 'reg copy HKLM\SOFTWARE\Python\PythonCore\2.7 HKLM\SOFTWARE\Python\PythonCore\2.7-32 /s /reg:32'
  - 'reg copy HKLM\SOFTWARE\Python\PythonCore\2.7 HKLM\SOFTWARE\Python\PythonCore\2.7-32 /s /reg:64'
build: off
test_script:
  - '%THEMIS_VIM% --version'
  - '%TEMP%\vim-themis\bin\themis.bat --runtimepath %TEMP%\vimproc --exclude ConcurrentProcess --reporter dot'
after_test:
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - pip install covimerage
  - covimerage write_coverage %THEMIS_PROFILE%
  - coverage xml
  - codecov -f coverage.xml

deploy: off
