name: depup
on:
  schedule:
    - cron: '35 9 2,13,25 * *' # Runs at 9:35 UTC 2,13,25 per month
  repository_dispatch:
    types: [depup]
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Check depup
        uses: haya14busa/action-depup@v1
        id: depup
        with:
          file: .github/actions/vital-throw-message/Dockerfile
          version_name: REVIEWDOG_VERSION
          repo: reviewdog/reviewdog

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          author: 'github-actions <41898282+github-actions[bot]@users.noreply.github.com>'
          title: "chore(deps): update ${{ steps.depup.outputs.repo }} to ${{ steps.depup.outputs.latest }}"
          commit-message: "chore(deps): update ${{ steps.depup.outputs.repo }} to ${{ steps.depup.outputs.latest }}"
          body: |
            Update ${{ steps.depup.outputs.repo }} to [${{ steps.depup.outputs.latest }}](https://github.com/${{ steps.depup.outputs.repo }}/releases/tag/v${{ steps.depup.outputs.latest }})

            This PR is auto generated by [depup workflow](https://github.com/${{ github.repository }}/actions?query=workflow%3A${{ github.workflow }}).
          branch: depup/${{ steps.depup.outputs.repo }}

  themis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Check depup
        uses: haya14busa/action-depup@v1
        id: depup
        with:
          file: ENVFILE
          version_name: THEMIS_VERSION
          repo: thinca/vim-themis
          tag: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          author: 'github-actions <41898282+github-actions[bot]@users.noreply.github.com>'
          title: "chore(deps): update ${{ steps.depup.outputs.repo }} to ${{ steps.depup.outputs.latest }}"
          commit-message: "chore(deps): update ${{ steps.depup.outputs.repo }} to ${{ steps.depup.outputs.latest }}"
          body: |
            Update ${{ steps.depup.outputs.repo }} to [${{ steps.depup.outputs.latest }}](https://github.com/${{ steps.depup.outputs.repo }}/releases/tag/v${{ steps.depup.outputs.latest }})

            This PR is auto generated by [depup workflow](https://github.com/${{ github.repository }}/actions?query=workflow%3A${{ github.workflow }}).
          branch: depup/${{ steps.depup.outputs.repo }}
